{
    parserClass="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.parser.SimpleParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Simple"
    psiImplClassSuffix="Impl"
    psiPackage="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.psi"
    psiImplPackage="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.psi"

    elementTypeHolderClass="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.psi.SimpleTypes"
    elementTypeClass="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.psi.SimpleElementType"
    tokenTypeClass="com.github.omtians9425.intellijcustomlanguagesupporttutorial.language.psi.SimpleTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY